export const data = [
  {
    tripID: "1234ASB",
    startCity: "Lagos",
    startBusStop: "BusStop",
    destinationCity: "Abuja",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-01",
    time: "08:00",
    driver: "Chika Okonkwo",
    vehicle: "Toyota Corolla",
  },
  {
    tripID: "1234YSB",
    startCity: "Port Harcourt",
    startBusStop: "BusStop",
    destinationCity: "Enugu",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-02",
    time: "09:00",
    driver: "Nnamdi Eze",
    vehicle: "Honda Accord",
  },
  {
    tripID: "1234ApB",
    startCity: "Abuja",
    startBusStop: "BusStop",
    destinationCity: "Lagos",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-03",
    time: "10:00",
    driver: "Uche Onwuka",
    vehicle: "Nissan Altima",
  },
  {
    tripID: "1234BpC",
    startCity: "Ibadan",
    startBusStop: "BusStop",
    destinationCity: "Kano",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-04",
    time: "11:00",
    driver: "Ogechi Okoro",
    vehicle: "Mitsubishi Outlander",
  },
  {
    tripID: "1234CpD",
    startCity: "Kaduna",
    startBusStop: "BusStop",
    destinationCity: "Benin City",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-05",
    time: "12:00",
    driver: "Folake Adeyemi",
    vehicle: "Ford Explorer",
  },
  {
    tripID: "1234ASB",
    startCity: "Lagos",
    startBusStop: "BusStop",
    destinationCity: "Abuja",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-01",
    time: "08:00",
    driver: "Chika Okoli",
    vehicle: "Toyota Corolla",
  },
  {
    tripID: "1234BpC",
    startCity: "Ibadan",
    startBusStop: "BusStop",
    destinationCity: "Kano",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-04",
    time: "11:00",
    driver: "Ogechi Okoro",
    vehicle: "Mitsubishi Outlander",
  },
  {
    tripID: "1234CpD",
    startCity: "Kaduna",
    startBusStop: "BusStop",
    destinationCity: "Benin City",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-05",
    time: "12:00",
    driver: "Folake Adeyemi",
    vehicle: "Ford Explorer",
  },
  {
    tripID: "1234ASB",
    startCity: "Lagos",
    startBusStop: "BusStop",
    destinationCity: "Abuja",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-01",
    time: "08:00",
    driver: "Chika Okoli",
    vehicle: "Toyota Corolla",
  },
  {
    tripID: "1234YSB",
    startCity: "Port Harcourt",
    startBusStop: "BusStop",
    destinationCity: "Ibadan",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-02",
    time: "09:00",
    driver: "Tolu Adewale",
    vehicle: "Honda Accord",
  },
  {
    tripID: "1234ApB",
    startCity: "Benin City",
    startBusStop: "BusStop",
    destinationCity: "Kano",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-03",
    time: "10:00",
    driver: "Nkem Ikechukwu",
    vehicle: "Nissan Altima",
  },
  {
    tripID: "1234CpB",
    startCity: "Enugu",
    startBusStop: "BusStop",
    destinationCity: "Jos",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-04",
    time: "11:00",
    driver: "Olufunmilayo Akinsola",
    vehicle: "Mitsubishi Lancer",
  },
  {
    tripID: "1234DpB",
    startCity: "Warri",
    startBusStop: "BusStop",
    destinationCity: "Calabar",
    destinationBusStop: "Stop BusStop",
    date: "2022-01-05",
    time: "12:00",
    driver: "Bolaji Adeyemi",
    vehicle: "Ford Focus",
  },
];
