export const data = [
  {
    tripID: "1234ASB",
    start: "Lagos",
    destination: "Abuja",
    date: "2022-01-01",
    time: "08:00",
    driver: "Chika Okonkwo",
    vehicle: "Toyota Corolla",
  },
  {
    tripID: "1234YSB",
    start: "Port Harcourt",
    destination: "Enugu",
    date: "2022-01-02",
    time: "09:00",
    driver: "Nnamdi Eze",
    vehicle: "Honda Accord",
  },
  {
    tripID: "1234ApB",
    start: "Abuja",
    destination: "Lagos",
    date: "2022-01-03",
    time: "10:00",
    driver: "Uche Onwuka",
    vehicle: "Nissan Altima",
  },
  {
    tripID: "1234BpC",
    start: "Ibadan",
    destination: "Kano",
    date: "2022-01-04",
    time: "11:00",
    driver: "Ogechi Okoro",
    vehicle: "Mitsubishi Outlander",
  },
  {
    tripID: "1234CpD",
    start: "Kaduna",
    destination: "Benin City",
    date: "2022-01-05",
    time: "12:00",
    driver: "Folake Adeyemi",
    vehicle: "Ford Explorer",
  },
  {
    tripID: "1234ASB",
    start: "Lagos",
    destination: "Abuja",
    date: "2022-01-01",
    time: "08:00",
    driver: "Chika Okoli",
    vehicle: "Toyota Corolla",
  },
  {
    tripID: "1234BpC",
    start: "Ibadan",
    destination: "Kano",
    date: "2022-01-04",
    time: "11:00",
    driver: "Ogechi Okoro",
    vehicle: "Mitsubishi Outlander",
  },
  {
    tripID: "1234CpD",
    start: "Kaduna",
    destination: "Benin City",
    date: "2022-01-05",
    time: "12:00",
    driver: "Folake Adeyemi",
    vehicle: "Ford Explorer",
  },
  {
    tripID: "1234ASB",
    start: "Lagos",
    destination: "Abuja",
    date: "2022-01-01",
    time: "08:00",
    driver: "Chika Okoli",
    vehicle: "Toyota Corolla",
  },
  {
    tripID: "1234YSB",
    start: "Port Harcourt",
    destination: "Ibadan",
    date: "2022-01-02",
    time: "09:00",
    driver: "Tolu Adewale",
    vehicle: "Honda Accord",
  },
  {
    tripID: "1234ApB",
    start: "Benin City",
    destination: "Kano",
    date: "2022-01-03",
    time: "10:00",
    driver: "Nkem Ikechukwu",
    vehicle: "Nissan Altima",
  },
  {
    tripID: "1234CpB",
    start: "Enugu",
    destination: "Jos",
    date: "2022-01-04",
    time: "11:00",
    driver: "Olufunmilayo Akinsola",
    vehicle: "Mitsubishi Lancer",
  },
  {
    tripID: "1234DpB",
    start: "Warri",
    destination: "Calabar",
    date: "2022-01-05",
    time: "12:00",
    driver: "Bolaji Adeyemi",
    vehicle: "Ford Focus",
  },
];
