export const banks = [
	"Access Bank",
	"Guaranty Trust Bank",
	"Zenith Bank",
	"United Bank for Africa",
	"First Bank of Nigeria",
	"Union Bank",
	"Fidelity Bank",
	"Sterling Bank",
	"Keystone Bank",
	"Wema Bank",
	"Ecobank Nigeria",
	"FCMB Group",
	"Heritage Bank",
	"Stanbic IBTC Bank",
	"Polaris Bank",
	"Aliko Dangote Group (African Export-Import Bank)",
	"Unity Bank",
	"Providus Bank",
	"Jaiz Bank",
	"Rand Merchant Bank Nigeria",
	"Coronation Merchant Bank",
	"FBNQuest Merchant Bank",
	"Standard Chartered Bank Nigeria",
	"Citibank Nigeria Limited",
	"Diamond Bank",
	"Enterprise Bank (Now Heritage Bank)",
	"Skye Bank (Now Polaris Bank)",
	"Mainstreet Bank (Now Polaris Bank)",
	"Oceanic Bank (Now Ecobank Nigeria)",
	"Afribank (Now Unity Bank)",
];